# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a448eeaad797a80ec94c60979849118586945d629ad1fc32796da24df3af8b95ad7f55f3a42388752c9247d0bb4d069d269ff9ee637053e90f7cf6444712e3

test:
  secret_key_base: 66f41ecbf2081f2f5a458266b499e93818433435ccf6f6ef08384cffc6f0a8e0a4ceb0757fdc5eee2b8d6c56755b4786c1714f7cf1d67c53fb2c5de0d7218e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
